services:
  app:
    image: mafumaful/golang:1.21
    build: 
      context: ./docker
      dockerfile: ./golang/Dockerfile
      target: dev
    volumes:
        - ./code:/home/docker/code
    tty: true